theme: jekyll-theme-architect

title: [javahelp]
description: [Online help for the Java Platform]

# sidebar links url
links:
  source: https://github.com/javaee/javahelp
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

